version: '3.9'

services:
  ai-learning-assistant:
    build: .
    ports:
      - "8888:8888"
    environment:
      - FLASK_ENV=production
      - PORT=8888
      - HOST=0.0.0.0

    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mlflow
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8888/api/health', timeout=5).getcode()==200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 可选：添加Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ai-learning-assistant
    restart: unless-stopped