name: CI

on:
  pull_request:
    branches: [ dev, staging, main ]
  push:
    branches: [ dev ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black
      - name: Lint (flake8)
        run: flake8 .
      - name: Format check (black)
        run: black --check .
      - name: Tests (pytest)
        run: pytest -q
      - name: Docker build
        run: docker build -t ai-learning-assistant:ci .
